server:
  port: 10001

spring:
  application:
    name: demo-spring-cloud-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
zuul:
  ignoredPatterns: /api/**
#  routes:
#    api-a:
#      path: /route-a/**
#      serviceId: demo-spring-cloud-feign
#    api-b:
#      path: /route-b/**
#      serviceId: demo-spring-cloud-ribbon