spring:
  application:
    name: demo-spring-cloud-ribbon

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream